services:

    redis:
        image: redis:6

    node:
        ports:
            - 5000:5000
        dockerfile: |
            FROM node:14.15
            RUN \
                mkdir -p /usr/src/app && \
                cd /usr/src/app && \
                npm init -y && \
                npm install redis
        workdir: /usr/src/app
        volumes:
            - ./app.js:/usr/src/app/index.js
        entrypoint: node
        cmd: index.js
