services:

    node:
        scale: 3
        image: node:14.15
        workdir: /usr/src/app
        volumes:
            - .:/usr/src/app
        cmd: node app.js

    nginx:
        ports:
            - 5000:5000
        build:
            - ./nginx.conf: |
                events {
                    worker_connections 1024;
                }
                http {
                    upstream node {
                        server node1:5000;
                        server node2:5000;
                        server node3:5000;
                    }
                    server {
                        listen 5000;

                        location / {
                            proxy_pass http://node;
                        }
                    }
                }
                daemon off;
            - Dockerfile: |
                FROM nginx:1.18
                ADD ./nginx.conf /etc/nginx/nginx.conf
        cmd: nginx
